services:
  - type: web
    name: happy-valentines
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:hzutKpmXOMnIdJqhmg7dBDJrAkVxqS7rteyabf6R6lk=
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
